### ISSUE TITLE
Rust version of `EventReplayRequested` incompatible with TS version

### ISSUE THREAD

**Issue by jamwaffles** [repositive/event-store-rs#60]
To integrate with the current TS event store (https://github.com/repositive/event-store), the TS version needs refactoring. The [current `EventReplayRequested` event shape](https://github.com/repositive/event-store/blob/master/src/index.ts#L56-L60) looks like this:

```typescript
interface EventReplayRequested extends EventData {
  type: 'EventReplayRequested';
  event_type: string;
  since: string; // ISO String
}
```

The `event_type` field in TS (which specifies which event should be emitted back out) conflicts with `event_type` in the Rust version, which is the un-namespaced event name of the _emitted_ event. Here's what the Rust version looks like:

```rust
struct EventReplayRequested {
    event_type: String,
    event_namespace: String,
    requested_event_type: String,
    requested_event_namespace: String,
    since: DateTime<Utc>,
}
```

### Here's a plan to fix this:

* Create a transitionary version of the TS event store where `EventReplayRequested` contains both the "old" `event_type` field _and_ the new `requested_*` fields to allow compatibility between unfixed and fixed releases of the TS event store:

  ```typescript
  interface EventReplayRequested extends EventData {
    type: 'EventReplayRequested';
    event_type: string;
    requested_event_type: string;
    requested_event_namespace: string;
    since: string; // ISO String
  }
  ```

  This will require changing the public API slightly to accept an event namespace and type as separate fields.

  The transitionary shape will allow consumers to be migrated to the new event shape using `requested_event_type` and `requested_event_namespace` instead of `event_type`.

* Once all clients of the TS event store have been migrated, change `EventReplayRequested` to look like this:

  ```typescript
  interface EventReplayRequested extends EventData {
    type: 'EventReplayRequested';
    event_namespace: 'eventstore';
    event_type: 'EventReplayRequested';
    requested_event_type: string;
    requested_event_namespace: string;
    since: string; // ISO String
  }
  ```

  At this point, there are no longer any name conflicts and the Rust event store can work alongside the TS version.

Any usage of the Rust event store with existing Repositive services is blocked by this issue, as is #8 to a lesser extent.

### Unresolved questions

* [x] ~There is no namespace for `EventReplayRequested`. Should there be one? If not, it would require changing the Rust event store to use `namespace: Option<String>` in event definitions. How would adding a global namespace affect RabbitMQ filtering?~ Solution: add `eventstore` namespace. This just changes the RabbitMQ queue name but has no other effects.

**Comment by Istar-Eldritch** [comment]
Sounds good. Should we add this to the TA backlog?

**Comment by jamwaffles** [comment]
> Should we add this to the TA backlog?

Yes, quick scoping sesh?

**Comment by jamwaffles** [comment]
Closing as fixed by all the other referenced PRs.
